version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    restart: on-failure
    environment:
      - DB_NAME=wishlist
      - DB_USER=wishlistuser
      - DB_PASSWORD=wishlistpass
      - DB_HOST=db
      - DB_PORT=5432
      - API_PRODUCTS_URL=https://challenge-api.luizalabs.com
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: wishlist
      POSTGRES_USER: wishlistuser
      POSTGRES_PASSWORD: wishlistpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  redis_data:
